name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # Permet de déclencher manuellement

permissions:
  contents: write
  actions: read

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Debug info
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Configure Git
        run: |
          git config --global user.name 'Health Check Bot'
          git config --global user.email 'action@github.com'
      - name: Make script executable
        run: chmod +x ./health-check.sh
      - name: Run Health Check
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Show logs (for debugging)
        run: |
          echo "=== Logs directory ==="
          ls -la logs/ || echo "No logs directory found"
          echo "=== Recent logs ==="
          find logs -name "*.log" -exec tail -5 {} \; || echo "No log files found"
